### ISSUE TITLE
Binary release ?

### ISSUE THREAD

**Issue by solsticedhiver** [rwmjones/rhsrvany#4]
Newbie here. ended up here because of error message of `virt-v2v`

```
virt-v2v: error: One of rhsrvany.exe or pvvxsvc.exe is missing in 
/usr/share/virt-tools.  One of them is required in order to install Windows 
firstboot scripts.  You can get one by building rhsrvany 
(https://github.com/rwmjones/rhsrvany)
```

How do I compile it ? It fails because of missing header windows.h. I tried instaling wine but that still fails.
do I need to compile this on windows ?

Is there any binary release ?

**Comment by rwmjones** [comment]
It is cross-compiled for a number of Linux distros including Fedora.  By following the links below you'll find instructions for cross-compiling it on Fedora or downloading a Fedora binary package.

https://src.fedoraproject.org/rpms/mingw-srvany/tree/rawhide
https://koji.fedoraproject.org/koji/packageinfo?packageID=13522

> do I need to compile this on windows ?

AIUI you *could* compile it on Windows, but we cross-compile it from Linux always.

**Comment by solsticedhiver** [comment]
You mean I have to hunt down inside the rpm for the .exe ?

Is it too much to ask for a bundle archive with the 2 exe here on github ?

**Comment by rwmjones** [comment]
We don't have a binary build of rhsrvany upstream or any place or way to maintain that, you'll have to cross-build it yourself or get it from a Linux distro that is already cross-building it.

**Comment by solsticedhiver** [comment]
For anyone interested, I did https://aur.archlinux.org/packages/mingw-w64-rhsrvany/

**Comment by telenieko** [comment]
For anyone interested, here's how I did it:

- Get the [latest RPM from Fedora](https://koji.fedoraproject.org/koji/packageinfo?packageID=13522) (you want the "noarch")
- Extract the files using `rpm2cpio` (this tool is available on pretty much any distro)

```sh
apt install rpm2cpio

wget -nd -O srvany.rpm https://kojipkgs.fedoraproject.org//packages/mingw-srvany/1.1/4.fc38/noarch/mingw32-srvany-1.1-4.fc38.noarch.rpm

rpm2cpio srvany.rpm | cpio -idmv
```

Which results in:

```
./usr/i686-w64-mingw32/sys-root/mingw/bin/pnp_wait.exe
./usr/i686-w64-mingw32/sys-root/mingw/bin/rhsrvany.exe
./usr/share/doc/mingw32-srvany
./usr/share/doc/mingw32-srvany/COPYING
```

**Comment by telenieko** [comment]
> We don't have a binary build of rhsrvany upstream or any place or way to maintain that, you'll have to cross-build it yourself or get it from a Linux distro that is already cross-building it.

@rwmjones I posted above instructions on how to fetch the binaries from Fedora. Given that `virt-v2v` redirects users to this repo (users who may have no clue on how to build this) maybe something along the lines of [my previous comment](https://github.com/rwmjones/rhsrvany/issues/4#issuecomment-1445372642) could be added to the README to guide users? I'd be happy to make a PR for that.

**Comment by rwmjones** [comment]
Yes please, let's document this.
